redis-ha:
  enabled: true

controller:
  replicas: 1


repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

certificate:
  enabled: true

server:
  service:
    type: NodePort
  ingress:
    enabled: false # Setting up an ingress here requires an domain to work properly with the ALB controller
  autoscaling:
    enabled: true
    minReplicas: 2

configs:
  params:
    server.insecure: true