redis-ha:
  enabled: true

controller:
  replicas: 1


repoServer:
  autoscaling:
    enabled: true
    minReplicas: 2

applicationSet:
  replicas: 2

certificate:
  enabled: true

server:
  service:
    type: NodePort
  ingress:
    enabled: true
    hostname: ""
    ingressClassName: alb
    tls: true
  autoscaling:
    enabled: true
    minReplicas: 2

configs:
  params:
    server.insecure: true