apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
spec:
  generators:
  - clusters: {} # Provision to all clusters
  template:
    metadata:
      name: 'crossplane'
    spec:
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
      project: default
      source:
        chart: crossplane
        repoURL: https://charts.crossplane.io/stable
        targetRevision: 1.18.0
        helm:
          values: |
            extraObjects: []
            - apiVersion: pkg.crossplane.io/v1alpha1
              kind: ControllerConfig
              metadata:
                name: aws-config
                annotations:
                  eks.amazonaws.com/role-arn: arn:aws:iam::107045546375:role/crossplane
                  helm.sh/hook: post-install
              spec:
                podSecurityContext:
                  fsGroup: 2000

      destination:
        server: "https://kubernetes.default.svc"
        namespace: crossplane-system