apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crossplane
  annotations:
    argocd.argoproj.io/sync-wave: "-99"
spec:
  generators:
  - clusters: {} # Provision to all clusters
  template:
    metadata:
      name: 'crossplane'
    spec:
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
      project: default
      source:
        chart: crossplane
        repoURL: https://charts.crossplane.io/stable
        targetRevision: 1.18.0
      destination:
        server: "https://kubernetes.default.svc"
        namespace: crossplane-system