apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aws-load-balancer-controller
spec:
  generators:
  - clusters: {} # Provision to all clusters
  template:
    metadata:
      name: 'aws-load-balancer-controller'
    spec:
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          allowEmpty: true
          selfHeal: true
      project: default
      source:
        chart: aws-load-balancer-controller
        repoURL: https://aws.github.io/eks-charts
        targetRevision: v1.9.2
        helm:
          values: |
            clusterName: '{{name}}'
            serviceAccount:
              name: '{{metadata.annotations.lbControllerArn}}'
              create: false
      destination:
        server: "https://kubernetes.default.svc"
        namespace: aws-lb-controller