apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: aws-config
  annotations:
    argocd.argoproj.io/sync-wave: "7"
    eks.amazonaws.com/role-arn: arn:aws:iam::767397804217:role/crossplane
spec:
  podSecurityContext:
    fsGroup: 2000
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::767397804217:role/crossplane