apiVersion: eks.aws.upbound.io/v1beta2
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: sample-eks-cluster
spec:
  forProvider:
    region: us-east-1
    vpcConfig:
      subnetIdRefs:
        - name: subnetattach-1