apiVersion: eks.aws.upbound.io/v1beta2
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: example
  annotations:
    argocd.argoproj.io/sync-wave: "99"
  name: sample-eks-cluster
spec:
  forProvider:
    region: us-east-1
    roleArnRef:
      name: sample-role
    vpcConfig:
      subnetIdRefs:
        - name: subnetattach-1
        - name: subnetattach-2