apiVersion: eks.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    testing.upbound.io/example-name: example
  name: sample-eks-cluster
spec:
  forProvider:
    region: us-east-1
    vpcConfig:
      - subnetIdRefs:
          - name: subnetattach-1