apiVersion: ec2.aws.upbound.io/v1beta1
kind: Subnet
metadata:
  name: subnetattach-1
spec:
  forProvider:
    availabilityZone: us-east-1b
    cidrBlock: 10.7.5.0/24
    region: us-east-1
    vpcIdSelector:
      matchLabels:
        purpose: eks